### ISSUE TITLE
Tag a release ?

### ISSUE THREAD

**Issue by tpetazzoni** [npitre/cramfs-tools#3]
Would it be possible to tag a 2.1 or 2.0.1 release with the current contents of master ? Indeed the fixes in 1a1e65f2a0491e07a32743af9a8e08f0d3b67e8e and ff80403acc3ecd821fadff2ebee3d26e57cf31f6 are quite nice to have. Thanks!

**Comment by npitre** [comment]
On Mon, 30 Sep 2019, Thomas Petazzoni wrote:

> Would it be possible to tag a 2.1 or 2.0.1 release with the current contents of master ?

Done.

**Comment by tpetazzoni** [comment]
Wow, thanks! :-)
