### ISSUE TITLE
Building with mingw

### ISSUE THREAD

**Issue by rweather** [npitre/cramfs-tools#4]
I had some warnings when compiling with "CC=i686-w64-mingw32-gcc make mkcramfs" that may be worth fixing in the main version.  The patch is pretty small, so I am including it here.  Undef PAGE_SIZE (which is set to 65536 in mingw's headers) and fix a warning with printf's parameters.

I wasn't able to get cramfsck to compile because of the ioctl(BLKGETSIZE) call but I don't need that.

diff --git a/mkcramfs.c b/mkcramfs.c
index 69045ae..e2f917f 100644
--- a/mkcramfs.c
+++ b/mkcramfs.c
@@ -81,6 +81,7 @@
 #define PAD_SIZE 512

 /* The kernel assumes PAGE_SIZE as block size. */
+#undef PAGE_SIZE
 #define PAGE_SIZE (4096)

 /*
@@ -1546,7 +1547,7 @@ int main(int argc, char **argv)
        /* Write the superblock now that we can fill in all of the fields. */
        write_superblock(root_entry, rom_image+opt_pad, offset);
        if (opt_verbose)
-               printf("Super block: %ld bytes\n", sizeof(struct cramfs_super));
+               printf("Super block: %ld bytes\n", (long)sizeof(struct cramfs_super));

        /* Put the checksum in. */
        crc = crc32(0L, Z_NULL, 0);

**Comment by npitre** [comment]
Thanks for the report. Fix pushed.
